asx_tickers:
  - BHP.AX
  - CBA.AX
  - CSL.AX
  - ANZ.AX
  - WBC.AX
  - NAB.AX
  - WES.AX
  - WOW.AX
  - MQG.AX
  - RIO.AX
  - FMG.AX
  - TLS.AX
  - REA.AX
  - SEK.AX
  - XRO.AX
  - COH.AX
  - QAN.AX
  - ALL.AX
  - AMC.AX
  - APA.AX
  - ASX.AX
  - AZJ.AX
  - BXB.AX
  - CAR.AX
  - CPU.AX

sp500_tickers:
  - AAPL
  - MSFT
  - GOOGL
  - AMZN
  - META
  - NVDA
  - JPM
  - JNJ
  - V
  - PG
  - UNH
  - HD
  - MA
  - BAC
  - XOM
  - PFE
  - KO
  - PEP
  - ABBV
  - MRK
  - LLY
  - CVX
  - TMO
  - ACN
  - NKE
